title: Adam Gao
description: Adam Gao's Portfolio
theme: just-the-docs

url: https://gaoadam.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Build settings
markdown: kramdown
math: katex